name: main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
  pull_request:

jobs:
  build:
    if: ${{ github.event_name != 'push' || github.ref != 'refs/heads/master'}}
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2
        with:
          path: temp
          fetch-depth: 0

      # to match the autobuild environment
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          install: VCS base-devel pactoys
          update: true

      - name: Add staging repo
        shell: msys2 {0}
        run: |
          sed -i '1s|^|[staging]\nServer = https://repo.msys2.org/staging/\nSigLevel = Never\n|' /etc/pacman.conf

      - name: Update using staging
        run: |
          msys2 -c 'pacman --noconfirm -Suuy'
          msys2 -c 'pacman --noconfirm -Suu'

      - name: Move Checkout
        run: |
          Copy-Item -Path ".\temp" -Destination "C:\_" -Recurse

      - name: CI-Build
        shell: msys2 {0}
        run: |
          cd /C/_
          ./.ci/ci-build.sh

      - name: "Upload binaries"
        uses: actions/upload-artifact@v2
        with:
          name: msys2-packages
          path: C:/_/artifacts/*.pkg.tar.*

      - name: "Upload sources"
        uses: actions/upload-artifact@v2
        with:
          name: sources
          path: C:/_/artifacts/*.src.tar.*

  release-packages:
    needs: [build]
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        continue-on-error: true
        with:
          name: msys2-packages
          path: C:/_/artifacts
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: packages
          artifacts: C:/_/artifacts/*.pkg.tar.*
          token: ${{ secrets.GITHUB_TOKEN }}

  release-sources:
    needs: [build]
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        continue-on-error: true
        with:
          name: sources
          path: C:/_/artifacts
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: sources
          artifacts: C:/_/artifacts/*.src.tar.*
          token: ${{ secrets.GITHUB_TOKEN }}
